name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Fetch Node Packages for module NLU
        working-directory: ./modules/nlu
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test
        env:
          PG_DB: postgres
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_PORT: 5432

  e2e:
    name: e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Build core, UI and modules
        run: |
          NODE_OPTIONS="--max-old-space-size=6000" yarn build
      - name: Run Tests
        run: |
          yarn start & sleep 5s &&
          HEADLESS=true BP_LICENSE_KEY=${{ secrets.BP_LICENSE_KEY }} JEST_TIMEOUT=30000 yarn itest
      - name: Upload Screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: screenshots
          path: build/tests/e2e/screenshots
